services:
  mongo:
    image: mongo:6.0
    container_name: ktln-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    networks:
      - db-net

volumes:
  mongo-data:
  mongo-config:
networks:
  db-net:
    driver: bridge
