# development stage
FROM node:20-alpine AS dev

WORKDIR /app

COPY package*.json ./
RUN npm install  

COPY . .

EXPOSE 8080

# RUN apk add --no-cache bash

CMD ["npm", "run", "dev"]

# production stage
FROM node:20-alpine AS prod
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE 8080

CMD ["npm", "start"]
